# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'course.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#############################################################
#                                                           #
#                       UI Generation                       #
#                                                           #
#############################################################

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog, listValues):
        Dialog.setObjectName("Dialog")
        Dialog.resize(510, 150)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 100, 471, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 471, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.txtCourseID = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtCourseID.setReadOnly(False)
        self.txtCourseID.setObjectName("txtCourseID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtCourseID)
        self.lblStudentCourseTitle = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblStudentCourseTitle.setObjectName("lblStudentCourseTitle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblStudentCourseTitle)
        self.txtCourseTitle = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtCourseTitle.setText("")
        self.txtCourseTitle.setObjectName("txtCourseTitle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtCourseTitle)
        self.lblCourseID = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblCourseID.setObjectName("lblCourseID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblCourseID)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # Update UI Here
        self.listValues = listValues
        self.initialSetup()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblStudentCourseTitle.setText(_translate("Dialog", "Course Title:"))
        self.lblCourseID.setText(_translate("Dialog", "Course ID:"))

    ##################### End UI Generation ###################

    def initialSetup(self):
        self.setValues()

    def setValues(self):
        if self.listValues == None:     #No list
            return

        self.txtCourseID.setText(self.listValues[0])
        self.txtCourseTitle.setText(self.listValues[1])

    def getValues(self):
        listResult = []
        listResult.append(self.txtCourseID.text())
        listResult.append(self.txtCourseTitle.text())
        return listResult

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog, None)
    Dialog.show()
    sys.exit(app.exec_())
