# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Exercise03.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#############################################################
#                                                           #
#                       UI Generation                       #
#                                                           #
#############################################################

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog, listValues):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 217)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(180, 150, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 40, 481, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lblCategoryID = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblCategoryID.setObjectName("lblCategoryID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblCategoryID)
        self.lblCategory = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblCategory.setObjectName("lblCategory")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblCategory)
        self.txtCategoryID = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtCategoryID.setReadOnly(True)
        self.txtCategoryID.setObjectName("txtCategoryID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtCategoryID)
        self.txtCategory = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtCategory.setObjectName("txtCategory")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtCategory)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # Update UI Here
        self.listValues = listValues
        self.initialSetup()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblCategoryID.setText(_translate("Dialog", "Category ID: "))
        self.lblCategory.setText(_translate("Dialog", "Category: "))

##################### End UI Generation ###################

    def initialSetup(self):
        self.setValues()

    def setValues(self):
        if self.listValues == None:     #No list
            return

        self.txtCategoryID.setText(self.listValues[0])
        self.txtCategory.setText(self.listValues[1])

    def getValues(self):
        listResult = []
        listResult.append(self.txtCategoryID.text())
        listResult.append(self.txtCategory.text())
        return listResult

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog, None)
    Dialog.show()
    sys.exit(app.exec_())
