# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Instructor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#############################################################
#                                                           #
#                       UI Generation                       #
#                                                           #
#############################################################

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog, listValues):
        Dialog.setObjectName("Dialog")
        Dialog.resize(272, 137)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 100, 251, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 251, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lblInstructorID = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblInstructorID.setObjectName("lblInstructorID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblInstructorID)
        self.txtInstructorID = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtInstructorID.setReadOnly(False)
        self.txtInstructorID.setObjectName("txtInstructorID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtInstructorID)
        self.lblInstructorName = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblInstructorName.setObjectName("lblInstructorName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblInstructorName)
        self.txtInstructorName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtInstructorName.setObjectName("txtInstructorName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtInstructorName)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # Update UI Here
        self.listValues = listValues
        self.initialSetup()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblInstructorID.setText(_translate("Dialog", "Instructor ID:"))
        self.lblInstructorName.setText(_translate("Dialog", "Name:"))

    ##################### End UI Generation ###################

    def initialSetup(self):
        self.setValues()

    def setValues(self):
        if self.listValues == None:     #No list
            return

        self.txtInstructorID.setText(self.listValues[0])
        self.txtInstructorName.setText(self.listValues[1])

    def getValues(self):
        listResult = []
        listResult.append(self.txtInstructorID.text())
        listResult.append(self.txtInstructorName.text())
        return listResult

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog, None)
    Dialog.show()
    sys.exit(app.exec_())
